### ISSUE TITLE
The generator is broken

### ISSUE THREAD

**Issue by baash05** [iamliamnorton/promise_pay#6]
$rails generate promise_pay:init baash05@gmail.com super_password1234 --test

Users/dave/.rvm/gems/ruby-2.2.1@work/gems/promise_pay-0.1.9/lib/generators/promise_pay/init_generator.rb:31:in `rescue in token': uninitialized constant PromisePay::RequestError (NameError)
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/promise_pay-0.1.9/lib/generators/promise_pay/init_generator.rb:29:in`token'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`each'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`invoke_all'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/commands/generate.rb:13:in`<top (required)>'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:130:in`generate_or_destroy'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
    from /Users/dave/.rvm/gems/ruby-2.2.1@work/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

**Comment by iamliamnorton** [comment]
Thanks for making me aware of this. I will address this issue https://github.com/iamliamnorton/promise_pay/pull/7

**Comment by iamliamnorton** [comment]
Hey I've updated the code so you should see the exception being raised as output from the generator.
